version: '2'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-test
    command: ["npm", "test"]
    environment:
      - NODE_ENV=development
      - DEBUG=vegable:*
      - RHOST=redis
    ports:
      - 3001:3001
    networks:
      - redis-net
    depends_on:
      - redis

  redis:
    image: redis
    command: ["redis-server"]
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - redis-net
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data

networks:
  redis-net:

volumes:
  redis-data:
